name: Build

on: [push]

jobs:
  build:
    timeout-minutes: 45

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build and test
        run: |
          export TF_API_KEY=${{ secrets.TF_API_KEY }}
          bash scripts/build.sh
        shell: bash